version: '3.7'

services:
  db:
    image: postgres
    container_name: "pgsql"
    restart: always
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: partitions_db
      PGDATA: /var/postgres_data
    volumes:
      - postgres_data:/var/postgres_data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
